extends Node
class_name WorldAudio
## Ambient soundscape (wind, river, birds, crickets, rain, stove fire) and
## positional one-shot effects. Sounds are generated by tools/generate_audio.py.
## Buses come from res://default_bus_layout.tres: Ambience, Water, Weather, SFX.
## Outdoor buses get a low-pass filter while the player is inside the cabin.
const DIR := "res://assets/audio/"
const MUFFLE_BUSES: Array[StringName] = [&"Ambience", &"Water", &"Weather"]
const OPEN_CUTOFF := 20000.0
const INDOOR_CUTOFF := 850.0
const STEP_DISTANCE := 1.7
var _wind: AudioStreamPlayer
var _birds: AudioStreamPlayer
var _crickets: AudioStreamPlayer
var _rain: AudioStreamPlayer
var _river: AudioStreamPlayer3D
var _lake: AudioStreamPlayer3D
var _fire: AudioStreamPlayer3D
var _stove: Node3D
var _river_timer := 0.0
var _river_target := Vector3.ZERO
var _river_placed := false
var _gust := 0.5
var _indoor := 0.0
var _step_dist := 0.0
var _last_feet := Vector3.ZERO
var _has_last_feet := false
var _doors: Array[Node3D] = []
var _door_sig: Dictionary = {}
var _door_still: Dictionary = {}
var _rng := RandomNumberGenerator.new()

func _ready() -> void:
	add_to_group("world_audio")
	_rng.randomize()
	call_deferred("_setup")

func _stream(sound: String, loop := false) -> AudioStreamWAV:
	var path := DIR + sound + ".wav"
	if not ResourceLoader.exists(path):
		return null
	var s := load(path) as AudioStreamWAV
	if s and loop:
		s = s.duplicate() as AudioStreamWAV
		s.loop_mode = AudioStreamWAV.LOOP_FORWARD
		s.loop_begin = 0
		s.loop_end = int(s.get_length() * s.mix_rate)
	return s

func _loop2d(sound: String, bus: StringName) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.name = sound.capitalize()
	p.stream = _stream(sound, true)
	p.volume_db = -80.0
	p.bus = bus
	add_child(p)
	if p.stream:
		p.play()
	return p

func _loop3d(sound: String, unit: float, max_d: float, bus: StringName) -> AudioStreamPlayer3D:
	var p := AudioStreamPlayer3D.new()
	p.name = sound.capitalize() + "Emitter"
	p.stream = _stream(sound, true)
	p.unit_size = unit
	p.max_distance = max_d
	p.volume_db = -80.0
	p.bus = bus
	add_child(p)
	if p.stream:
		p.play()
	return p

func _setup() -> void:
	_wind = _loop2d("wind", &"Ambience")
	_birds = _loop2d("birds", &"Ambience")
	_crickets = _loop2d("crickets", &"Ambience")
	_rain = _loop2d("rain", &"Weather")
	_river = _loop3d("river", 7.0, 45.0, &"Water")
	_lake = _loop3d("river", 10.0, 55.0, &"Water")
	_lake.pitch_scale = 0.8
	_fire = _loop3d("fire", 2.5, 14.0, &"SFX")
	var ground := get_node_or_null("../Ground")
	if ground and ground.has_method("lake_center"):
		var c: Vector2 = ground.call("lake_center")
		_lake.global_position = Vector3(c.x, float(ground.call("lake_level")) + 0.3, c.y)
	for n in get_tree().root.find_children("*", "", true, false):
		if _stove == null and n is Node3D and n.has_method("heat_strength"):
			_stove = n
		var sc = n.get_script()
		if n is Node3D and sc is Script and String(sc.resource_path).ends_with("cabin_door.gd"):
			_doors.append(n)
			_door_sig[n] = _door_signature(n)
			_door_still[n] = 1.0
	if _stove:
		_fire.global_position = _stove.global_position + Vector3(0, 0.6, 0)

func _fade(p: Node, target_db: float, delta: float) -> void:
	if p == null or p.get("stream") == null:
		return
	p.set("volume_db", lerpf(float(p.get("volume_db")), target_db, clampf(delta * 1.2, 0.0, 1.0)))

func _is_inside(atmo: Node) -> bool:
	if atmo and atmo.has_method("_inside_cabin"):
		return bool(atmo.call("_inside_cabin"))
	return false

func _process(delta: float) -> void:
	var pl := get_node_or_null("../Player") as Node3D
	if pl == null or _wind == null:
		return
	var day := SurvivalState.get_daylight()
	var atmo := get_node_or_null("../Atmosphere")
	var rain := 0.0
	if atmo and atmo.get("_rain_strength") != null:
		rain = float(atmo.get("_rain_strength"))
	_indoor = move_toward(_indoor, 1.0 if _is_inside(atmo) else 0.0, delta * 1.2)
	_apply_muffle()
	# Small volume drop as well, because web builds may not run bus effects.
	var muffle := -5.0 * _indoor
	_gust = lerpf(_gust, _rng.randf(), delta * 0.3)
	_fade(_wind, -24.0 + clampf(pl.global_position.y / 10.0, 0.0, 1.0) * 7.0 + _gust * 5.0 + rain * 4.0 + muffle, delta)
	_fade(_birds, (-15.0 + muffle) if day > 0.45 and rain < 0.35 else -80.0, delta * 0.5)
	_fade(_crickets, (-19.0 + muffle) if day < 0.22 and rain < 0.5 else -80.0, delta * 0.5)
	_fade(_rain, (linear_to_db(maxf(rain, 0.0001)) - 6.0 + muffle * 0.6) if rain > 0.02 else -80.0, delta)
	_fade(_river, -4.0 + muffle, delta)
	_fade(_lake, -9.0 + muffle, delta)
	_river_timer -= delta
	if _river_timer <= 0.0:
		_river_timer = 0.25
		_place_river(pl)
	if _river_placed and _river:
		_river.global_position = _river.global_position.lerp(_river_target, clampf(delta * 1.5, 0.0, 1.0))
	if _stove and _fire:
		var active = _stove.get("active")
		var s := 0.0
		if active == null or bool(active):
			s = float(_stove.call("heat_strength"))
		_fade(_fire, (linear_to_db(maxf(s, 0.0001)) - 2.0) if s > 0.03 else -80.0, delta * 2.0)
	_update_steps(pl)
	_update_doors(delta)

func _apply_muffle() -> void:
	var cutoff := OPEN_CUTOFF * pow(INDOOR_CUTOFF / OPEN_CUTOFF, _indoor)
	for b in MUFFLE_BUSES:
		var idx := AudioServer.get_bus_index(b)
		if idx < 0 or AudioServer.get_bus_effect_count(idx) == 0:
			continue
		var fx := AudioServer.get_bus_effect(idx, 0) as AudioEffectLowPassFilter
		if fx == null:
			continue
		fx.cutoff_hz = cutoff
		AudioServer.set_bus_effect_enabled(idx, 0, _indoor > 0.01)

# Footsteps: grass outside, wooden floor inside the cabin.
func _update_steps(pl: Node3D) -> void:
	var body := pl as CharacterBody3D
	if body == null or not body.is_on_floor():
		_has_last_feet = false
		return
	var feet := pl.global_position
	if not _has_last_feet:
		_last_feet = feet
		_has_last_feet = true
		return
	var moved := Vector2(feet.x - _last_feet.x, feet.z - _last_feet.z).length()
	_last_feet = feet
	if moved > 2.0:
		return
	_step_dist += moved
	if _step_dist >= STEP_DISTANCE:
		_step_dist = 0.0
		var wood := _indoor > 0.5
		play_at("step_wood" if wood else "step_grass", feet, -10.0 if wood else -13.0, 0.12)

# Door sound plays when a cabin door starts moving after resting.
func _door_signature(d: Node3D) -> float:
	var s := d.rotation.length()
	for c in d.get_children():
		if c is Node3D:
			s += (c as Node3D).rotation.length() + (c as Node3D).position.length()
	return s

func _update_doors(delta: float) -> void:
	for d in _doors:
		if not is_instance_valid(d):
			continue
		var sig := _door_signature(d)
		var moving := absf(sig - float(_door_sig[d])) > 0.0005
		_door_sig[d] = sig
		if moving:
			if float(_door_still[d]) > 0.35:
				play_at("door", d.global_position + Vector3(0, 1.0, 0), -6.0, 0.06)
			_door_still[d] = 0.0
		else:
			_door_still[d] = float(_door_still[d]) + delta

# The river emitter follows the point of the river nearest to the player.
# The target is smoothed in _process so the sound does not jump.
func _place_river(pl: Node3D) -> void:
	var ground := get_node_or_null("../Ground")
	if ground == null or not ground.has_method("river_path") or _river == null:
		return
	var pts: PackedVector2Array = ground.call("river_path")
	var p := Vector2(pl.global_position.x, pl.global_position.z)
	var best := INF
	var bp := Vector2.ZERO
	for i in range(pts.size() - 1):
		var a := pts[i]
		var d := pts[i + 1] - a
		var r := clampf((p - a).dot(d) / maxf(d.length_squared(), 0.0001), 0.0, 1.0)
		var q := a + d * r
		var dist := p.distance_to(q)
		if dist < best:
			best = dist
			bp = q
	var info: Vector2 = ground.call("river_info", bp)
	_river_target = Vector3(bp.x, float(ground.call("river_level", info.y)) + 0.3, bp.y)
	if not _river_placed:
		_river.global_position = _river_target
		_river_placed = true

func play_at(sound: String, pos: Vector3, volume_db := 0.0, pitch_var := 0.08, bus: StringName = &"SFX") -> void:
	var s := _stream(sound)
	if s == null:
		return
	var p := AudioStreamPlayer3D.new()
	p.stream = s
	p.volume_db = volume_db
	p.unit_size = 4.0
	p.max_distance = 40.0
	p.bus = bus
	p.pitch_scale = 1.0 + _rng.randf_range(-pitch_var, pitch_var)
	add_child(p)
	p.global_position = pos
	p.play()
	p.finished.connect(p.queue_free)
